export const CREATE_POST = 'CREATE_POST'
export const FETCH_POST = 'FETCH_POST'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HEDE_LOADER = 'HEDE_LOADER'
export const SHOW_ERROR = 'SHOW_ERROR'
export const HEDE_ERROR = 'HEDE_ERROR '